baseURL = "https://cieramartinez.org/"
languageCode = "en-us"
title = "Ciera Martinez"

[markup.goldmark.renderer]
  unsafe = true

disableKinds = ["taxonomy", "term"]

[params]
  description = "Senior Program Manager at the Schmidt Center for Data Science and Environment, UC Berkeley"
  github = "https://github.com/iamciera"
  twitter = "https://twitter.com/CieraReports"
  scholar = "https://scholar.google.com/citations?user=JGUnmZoAAAAJ&hl=en&oi=ao"
  email = "ccmartinez@berkeley.edu"

[menu]
  [[menu.main]]
    name = "Portfolio"
    url = "/work/"
    weight = 1
  [[menu.main]]
    name = "Community"
    url = "/coalitions/"
    weight = 2
  [[menu.main]]
    name = "Training"
    url = "/training/"
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4
